export enum Permission {
  // USER
  USER_CREATE = 'USER_CREATE',
  USER_READ = 'USER_READ',
  USER_LIST = 'USER_LIST',
  USER_DROPDOWN_LIST = 'USER_DROPDOWN_LIST',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // PATIENT
  PATIENT_CREATE = 'PATIENT_CREATE',
  PATIENT_READ = 'PATIENT_READ',
  PATIENT_LIST = 'PATIENT_LIST',
  PATIENT_DROPDOWN_LIST = 'PATIENT_DROPDOWN_LIST',
  PATIENT_UPDATE = 'PATIENT_UPDATE',
  PATIENT_DELETE = 'PATIENT_DELETE',

  // CLAIM
  CLAIM_CREATE = 'CLAIM_CREATE',
  CLAIM_READ = 'CLAIM_READ',
  CLAIM_LIST = 'CLAIM_LIST',
  CLAIM_UPDATE = 'CLAIM_UPDATE',
  CLAIM_ASSIGN = 'CLAIM_ASSIGN',
  CLAIM_DELETE_DRAFT = 'CLAIM_DELETE_DRAFT',

  // FILE
  FILE_SINGLE_UPLOAD = 'FILE_SINGLE_UPLOAD',
  FILE_BULK_UPLOAD = 'FILE_BULK_UPLOAD',

  // COMMENT
  COMMENT_CREATE = 'COMMENT_CREATE',
  COMMENT_LIST = 'COMMENT_LIST',
  COMMENT_MARK_READ = 'COMMENT_MARK_READ',
  COMMENT_MANAGER_LIST = 'COMMENT_MANAGER_LIST',
  COMMENT_MANAGER_CHAT_UNREAD_COUNT = 'COMMENT_MANAGER_CHAT_UNREAD_COUNT',

  // DASHBOARD
  DASHBOARD_READ = 'DASHBOARD_READ',

  // ENHANCEMENTS
  ENHANCEMENT_CREATE = 'ENHANCEMENT_CREATE',
  ENHANCEMENT_UPDATE = 'ENHANCEMENT_UPDATE',

  // QUERIES
  QUERY_CREATE = 'QUERY_CREATE',
  QUERY_UPDATE = 'QUERY_UPDATE',

  // NOTIFICATIONS
  NOTIFICATION_READ_LIST = 'NOTIFICATION_READ_LIST',
  NOTIFICATION_MARK_READ = 'NOTIFICATION_MARK_READ',
}