import { Role } from '@prisma/client';
import { Permission } from './permissions.enum';

export const RolePermissions: Record<Role, Permission[]> = {
  SUPER_ADMIN: [
    Permission.USER_CREATE,
    Permission.USER_READ,
    Permission.USER_LIST,
    Permission.USER_DROPDOWN_LIST,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    // patients
    // claims
    // Permission.CLAIM_CREATE,
    Permission.CLAIM_READ,
    Permission.CLAIM_LIST,
    Permission.CLAIM_UPDATE,
    Permission.CLAIM_ASSIGN,
    Permission.CLAIM_DELETE_DRAFT,
    // files
    Permission.FILE_SINGLE_UPLOAD,
    Permission.FILE_BULK_UPLOAD,
    // comments
    Permission.COMMENT_CREATE,
    Permission.COMMENT_LIST,
    Permission.COMMENT_MARK_READ,
    Permission.COMMENT_MANAGER_LIST,
    Permission.COMMENT_MANAGER_CHAT_UNREAD_COUNT,
    // dashboard
    Permission.DASHBOARD_READ,
    // enhancements
    Permission.ENHANCEMENT_CREATE,
    Permission.ENHANCEMENT_UPDATE,
    // queries
    Permission.QUERY_CREATE,
    Permission.QUERY_UPDATE,
    // notifications
    Permission.NOTIFICATION_READ_LIST,
    Permission.NOTIFICATION_MARK_READ,
  ],
  ADMIN: [
    Permission.USER_CREATE,
    Permission.USER_READ,
    Permission.USER_LIST,
    Permission.USER_DROPDOWN_LIST,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    // Permission.CLAIM_CREATE,
    Permission.CLAIM_READ,
    Permission.CLAIM_LIST,
    Permission.CLAIM_UPDATE,
    Permission.CLAIM_ASSIGN,
    Permission.CLAIM_DELETE_DRAFT,
    Permission.FILE_SINGLE_UPLOAD,
    Permission.FILE_BULK_UPLOAD,
    Permission.COMMENT_CREATE,
    Permission.COMMENT_LIST,
    Permission.COMMENT_MARK_READ,
    Permission.COMMENT_MANAGER_LIST,
    Permission.COMMENT_MANAGER_CHAT_UNREAD_COUNT,
    Permission.DASHBOARD_READ,
    Permission.ENHANCEMENT_CREATE,
    Permission.ENHANCEMENT_UPDATE,
    Permission.QUERY_CREATE,
    Permission.QUERY_UPDATE,
    Permission.NOTIFICATION_READ_LIST,
    Permission.NOTIFICATION_MARK_READ,
  ],
  HOSPITAL: [
    Permission.USER_READ,
    Permission.PATIENT_CREATE,
    Permission.PATIENT_READ,
    Permission.PATIENT_LIST,
    Permission.PATIENT_DROPDOWN_LIST,
    Permission.PATIENT_UPDATE,
    Permission.PATIENT_DELETE,
    Permission.CLAIM_CREATE,
    Permission.CLAIM_READ,
    Permission.CLAIM_LIST,
    Permission.CLAIM_UPDATE,
    Permission.CLAIM_DELETE_DRAFT,
    Permission.FILE_SINGLE_UPLOAD,
    Permission.FILE_BULK_UPLOAD,
    Permission.COMMENT_CREATE,
    Permission.COMMENT_LIST,
    Permission.DASHBOARD_READ,
    Permission.ENHANCEMENT_CREATE,
    Permission.ENHANCEMENT_UPDATE,
    Permission.QUERY_CREATE,
    Permission.QUERY_UPDATE,
    Permission.NOTIFICATION_READ_LIST,
    Permission.NOTIFICATION_MARK_READ,
  ],
  HOSPITAL_MANAGER: [
    Permission.USER_READ,
    Permission.PATIENT_CREATE,
    Permission.PATIENT_READ,
    Permission.PATIENT_LIST,
    Permission.PATIENT_DROPDOWN_LIST,
    Permission.PATIENT_UPDATE,
    Permission.PATIENT_DELETE,
    Permission.CLAIM_CREATE,
    Permission.CLAIM_READ,
    Permission.CLAIM_LIST,
    Permission.CLAIM_UPDATE,
    Permission.CLAIM_DELETE_DRAFT,
    Permission.FILE_SINGLE_UPLOAD,
    Permission.FILE_BULK_UPLOAD,
    Permission.COMMENT_CREATE,
    Permission.COMMENT_LIST,
    Permission.COMMENT_MANAGER_CHAT_UNREAD_COUNT,
    Permission.DASHBOARD_READ,
    Permission.ENHANCEMENT_CREATE,
    Permission.ENHANCEMENT_UPDATE,
    Permission.QUERY_CREATE,
    Permission.QUERY_UPDATE,
    Permission.NOTIFICATION_READ_LIST,
    Permission.NOTIFICATION_MARK_READ,
  ],
};
